export default () => {
    return (
        <div>
            <h2 style={{ textAlign: 'center' }}>Terms of Service</h2>
            <p>Referendum 2.0 at https://ventvoila.com</p>
            <p style={{ textAlign: 'justify' }}>These Terms of Service govern your access to and use of the service (“Referendum 2.0”), and any information, text, graphics, photos or other materials uploaded, downloaded or appearing on the services is collectively said as "content". Your access to and use of the services are conditioned on your acceptance of and compliance with these terms. By accessing or using the services, you comply with these terms.</p>
            <p style={{ textAlign: 'justify' }}>1. Basic Terms</p>
            <p style={{ textAlign: 'justify' }}>You are responsible for your use of the service for any content you post to the service and for any consequences thereof. The contents you submit, post, or displays are going to be ready to be viewed by other users of the services and through third party services. You should only provide content that you simply are comfortable sharing with others under these terms.</p>
            <p style={{ textAlign: 'justify' }}>You may use the services as long as you'll be able to form a binding contract with Referendum 2.0 and aren't someone barred from receiving services under the laws or other applicable jurisdiction. If you're accepting these terms and using the service, you'll use the service only in compliance with these terms and terms of applicable local, state, national, and international laws, rules and regulations.</p>
            <p style={{ textAlign: 'justify' }}>The services that Referendum 2.0 provides are always evolving and, therefore, the form and nature of the services that Referendum 2.0 provides may change from time to time without prior notice to you. Additionally, Referendum 2.0 may stop (permanently or temporarily) providing the services (or any features within the Services) to you or to users generally and will not be able to provide you with prior notice. We also retain the right to form limits on use and storage at our sole discretion at any time without prior notice to you.</p>
            <p style={{ textAlign: 'justify' }}>The services may include advertisements, which can be targeted to the contents or information on the service queries made through the Service or other information. The categories and extent of advertising in Referendum 2.0 on the Services are subject to alteration. In consideration of Referendum 2.0 granting you access to and use of the service, you agree that Referendum 2.0 and</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;its third party providers and partners may place such advertising on the services or in reference to the display of contents or information from the services, whether submitted by you or others.</p>
            <p style={{ textAlign: 'justify' }}>2. Privacy</p>
            <p style={{ textAlign: 'justify' }}>Any information that you just provide to Referendum 2.0 is subject to our Privacy Policy, which governs our collection and use of your information. You understand that through your use of the services you consent to the gathering and use as set forth within the Privacy Policy of this information, including the transfer of this information, for storage, processing and use by Referendum 2.0. As a part of providing you with the service, we might have to produce you with certain communications, like service announcements and administrative messages. These communications are considered a part of the services and your Referendum 2.0 account, which you'll not be ready to opt-out from receiving.</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>3. Passwords</p>
            <p style={{ textAlign: 'justify' }}>You are answerable for safeguarding the password that you just use to access the services and for any activities or actions under your password. We encourage you to use "strong" passwords that use a mix of upper and lower-case letters, numbers and symbols) together with your account. Referendum 2.0 cannot and cannot be chargeable for any loss or damage arising from your failure to adjust to the above.</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>4. Content on the Services</p>
            <p style={{ textAlign: 'justify' }}>All content, whether publicly posted or privately transmitted, is the sole responsibility of the one who originated such content. We might not monitor or control the content posted via the services and, we cannot take responsibility for such content. Any use or reliance on any content or materials posted via the services or obtained by you through the services is at your own risk. We don't endorse, support, represent or guarantee the completeness, truthfulness, accuracy, or reliability of any content or communications posted via the services or endorse any opinions expressed via the services. You understand that by using the service you'll be exposed to content which may be offensive, harmful, inaccurate or otherwise inappropriate, or in some cases, postings that are mislabeled or are otherwise deceptive. under no circumstances will referendum 2.0 be liable in any way for any content, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a results of the utilization of any content posted, emailed, transmitted or otherwise made available via the services or broadcast elsewhere.</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>5. Your Rights</p>
            <p style={{ textAlign: 'justify' }}>You retain your rights to any content you submit or display on or through the services. By submitting, posting or displaying content on or through the service, you grant us a worldwide, non-exclusive, royalty-free license to use, copy, reproduce, process, adapt, modify, publish, transmit, display and distribute such content in any and every &nbsp;media or distribution method.</p>
            <p style={{ textAlign: 'justify' }}>You agree that this license includes the right for Referendum 2.0 to produce, promote, and improve the services and to create content submitted to or through the services available to other companies, organizations or individuals who partner with Referendum 2.0 for the syndication, broadcast, distribution or publication of such content on other media and service subject to our terms and conditions for such content use. These rules exist to enable an open ecosystem together with your rights in mind. But what’s yours is yours – you own your content. Such additional uses by Referendum 2.0, or other companies, organizations or individuals who partner with Referendum 2.0, is also made with no compensation paid to you with regard to the content that you just submit post, transmit or otherwise make available through the services.</p>
            <p style={{ textAlign: 'justify' }}>We may modify or adapt your content so as to transmit, display or distribute it over computer networks and in various media and/or make changes to your content as they are necessary to adapt and adapt that content to any requirements or limitations of any networks, devices, services or media.</p>
            <p style={{ textAlign: 'justify' }}>You are accountable for your use of the service for any content you provide, and for any consequences thereof, including the employment of your content by other users and our third party partners. You understand that your content is also syndicated, broadcast, distributed, or published by our partners and if you do not have the proper ability to submit content for such use, it should subject you to liability. Referendum 2.0 won't be responsible or chargeable for any use of your content by Referendum 2.0 in accordance with these terms. You represent and warrant that you simply have all the rights, power and authority necessary to grant the rights granted herein to any contents that you simply submit.</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>6. Your License to Use the Services</p>
            <p style={{ textAlign: 'justify' }}>Referendum 2.0 gives you a private, worldwide, royalty-free, non-assignable and non-exclusive license to use the software that's provided to you by Referendum 2.0 as a part of the services. This license is for the only real purpose of enabling you to use and revel in the advantages of the services as provided by Referendum 2.0, in the manner permitted by these terms.</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>7. Referendum 2.0 Rights</p>
            <p style={{ textAlign: 'justify' }}>All right, title, and interest in and to the services (excluding content provided by users) are and can remain the exclusive property of Referendum 2.0. The services are protected by applicable laws. Nothing within the terms gives you a right to use the Referendum 2.0 name or any of the Referendum 2.0 trademarks, logos, domain names, and other distinctive brand features. Any feedback, comments, or suggestions you will provide regarding Referendum 2.0, or the services is entirely voluntary and that we are unengaged to use such feedback, comments or suggestions as we see fit and with none obligation to you.</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>8. Restrictions on Content and Use of the Services</p>
            <p style={{ textAlign: 'justify' }}>We reserve the least time to get rid of or refuse to distribute any content on the service, to suspend or terminate users, and to reclaim usernames without liability to you. We also reserve the proper to access, read, preserve, and disclose any information as we reasonably believe is important to (i) satisfy any applicable law, regulation, legal process or governmental request, (ii) enforce the Terms, including investigation of potential violations hereof, (iii) detect, prevent, or otherwise address fraud, security or technical issues, (iv) reply to user support requests, or (v) protect the rights, property or safety of Referendum 2.0, its users and therefore the public. you will not do any of the subsequent while accessing or using the services: (i) access, tamper with, or use nonpublic areas of the service Referendum 2.0’s computer systems, or the technical delivery systems of Referendum 2.0’s providers; (ii) probe, scan, or test the vulnerability of any system or network or breach or circumvent any security or authentication measures; (iii) access or search or try and access or search the services by any means; automated or otherwise apart from through our currently available, published interfaces that are provided by Referendum 2.0 and only pursuant to those terms and conditions, unless you have got been specifically allowed to try to &nbsp;so in a very separate agreement with Referendum 2.0 (NOTE: crawling the services is permissible if worn out accordance with the provisions of the robots.txt file, however, scraping the services without the prior consent of Referendum 2.0 is expressly prohibited); (iv) forge any TCP/IP packet header or any a part of the header information in any email or posting, or in any way use the services to send altered, deceptive or false source-identifying information; or (v) interfere with, or disrupt, the access of any user, host or network, including, without limitation, sending a pestilence, overloading, flooding, spamming, mail-bombing the service or by scripting the creation of content in such a way on interfere with or create an undue burden on the Services.</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>9. Copyright Policy</p>
            <p style={{ textAlign: 'justify' }}>Referendum 2.0 respects the material possession rights of others and expects users of the services to try the identical. We are going to answer notices of alleged infringement that go with applicable law and are properly provided to us. If you suspect that your content has been copied in a very way that constitutes infringement of copyright, please provide us with the subsequent information: (i) a physical or electronic signature of the copyright owner or an individual authorized to act on their behalf; (ii) identification of the copyrighted work claimed to own been infringed; (iii) identification of the fabric that's claimed to be infringing or to be the topic of infringing activity which is to be removed or access to which is to be disabled, and knowledge reasonably sufficient to allow us to locate the material; (iv) your contact information, including your address, number, and an email address; (v) an announcement by you that you simply have a decent faith belief that use of the fabric within the manner complained of isn't authorized by the copyright owner, its agent, or the law; and (vi) an announcement that the knowledge within the notification is accurate, and, under penalty of perjury, that you simply are authorized to act on behalf of the copyright owner. We reserve the property to get rid of content purported to be infringing without prior notice, at our sole discretion, and without liability to you. In appropriate circumstances, Referendum 2.0 will terminate a user’s account if the user is decided to be a repeat infringer.&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>10. Ending These Terms</p>
            <p style={{ textAlign: 'justify' }}>The terms will still apply until terminated by either you or Referendum 2.0, as follows, as you may end your legal agreement with Referendum 2.0 at any time for any reason by deactivating your accounts. &nbsp;We may suspend or terminate your accounts or cease providing you with all or a part of the services at any time for any reason, including, but not limited to, if we reasonably believe: (i) you have violated these terms or the Referendum 2.0 Rules, (ii) you create risk or possible legal exposure for us; or (iii) our provision of the services to you is not any longer viable. We’ll make reasonable efforts to notify you by the e-mail address related to your account or the subsequent time you try to access your account.</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>11. Disclaimers and Limitations of Liability&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>Please read this section carefully since it limits the liability of Referendum 2.0. Each of the subsections below only applies up to the most extent permitted under applicable law. Some jurisdictions don't allow the disclaimer of implied warranties or the limitation of liability in contracts,</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;and as a result, the contents of this section might not apply to you. Nothing in this section is meant to limit any rights you have which cannot be lawfully limited.</p>
            <p style={{ textAlign: 'justify' }}>A. The Service - AS-IS</p>
            <p style={{ textAlign: 'justify' }}>Your access to and use of the services or any content is at your own risk. You understand and agree that the services are provided to you on an "AS IS" and "AS AVAILABLE" basis. Without limiting the foregoing, to the most extent permitted under applicable law, referendum 2.0 disclaims all warranties and conditions, whether express or implied, of merchantability, fitness for a selected purpose, or non-infringement. The Referendum 2.0 has no warranty and disclaims all responsibility and liability for: (i) the completeness, accuracy, availability, timeliness, security or reliability of the services or any content; (ii) any harm to your computer system, loss of data, or other harm that results from your access to or use of the services or any content; (iii) the deletion of, or the failure to store or to transmit, any content and other communications maintained by the services; and (iv) whether the services will meet your requirements or be available on an uninterrupted, secure, or error-free basis.&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>B. Links</p>
            <p style={{ textAlign: 'justify' }}>The services may contain links to third-party websites or resources. You acknowledge and agree that Referendum 2.0 doesn’t seem to be responsible or liable for: (i) the supply or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources don't imply any endorsement by Referendum 2.0 of such websites or resources or the content, products, or services available from such websites or resources. You acknowledge sole responsibility for and assume all risks arising from your use of any such websites or resources.</p>
            <p style={{ textAlign: 'justify' }}>C. Limitation of Liability</p>
            <p style={{ textAlign: 'justify' }}>To the utmost extent permitted by applicable law, the referendum 2.0 shall not be accountable for any indirect, incidental, special, consequential or indemnity, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of knowledge, use, good-will, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the services; (ii) any conduct or content of any third party on the service including without limitation, any defamatory, offensive or illegal conduct of other users or third parties; (iii) any content obtained from the services; or (iv) unauthorized access, use or alteration of your transmissions or content.&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>The &nbsp;restrictions of this subsection shall apply to any theory of liability, whether supported warranty, contract, statute, tort (including negligence) or otherwise and whether or not the referendum 2.0 a are informed of the likelihood of any such damage, and whether or not a remedy set forth herein is found to possess failed of its essential purpose.</p>
            <p style={{ textAlign: 'justify' }}>&nbsp;</p>
            <p style={{ textAlign: 'justify' }}>12. General Terms</p>
            <p style={{ textAlign: 'justify' }}>A. Waiver and Severability</p>
            <p style={{ textAlign: 'justify' }}>The failure of Referendum 2.0 to enforce any right or provision of those terms won't be deemed a waiver of such right or provision. In the event that any provision of those terms is held to be invalid or unenforceable, then that provision are limited or eliminated to the minimum extent necessary, and also, the remaining provisions of those terms will remain fully forced and effective.</p>
            <p style={{ textAlign: 'justify' }}>B. Controlling Law and Jurisdiction</p>
            <p style={{ textAlign: 'justify' }}>These terms and any action related thereto are governed by the applicable laws without respect to or application of its conflict of law provisions or your state or country of residence.</p>
            <p style={{ textAlign: 'justify' }}>C. Entire Agreement</p>
            <p style={{ textAlign: 'justify' }}>These terms, the Referendum 2.0 Rules and our Privacy Policy are the complete and exclusive agreement between Referendum 2.0 and you regarding the services. We may revise these terms from time to time; the foremost current version will always be at https://ventvoila.com/tos. If the revision, in our sole discretion, is material, we'll notify you via Referendum 2.0 update or e-mail to the e-mail related to your account. By continuing to access or use the services after those revisions become effective, you comply with being bound by the revised terms.</p>
            <p style={{ textAlign: 'justify' }}>If you've got any questions on these terms, please contact us at,</p>
            <p style={{ textAlign: 'justify' }}>Email: contacts@ventvoila.com</p>
        </div>
    )
}