const ActionTypes = {
    PROFILE: "PROFILE",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    MENU: "MENU",
    NAV_PATH: "NAV_PATH",
    FEED_LIST: "FEED_LIST",
    FEED_LIST_RESET: "FEED_LIST_RESET",
    VEND_LIST: "VEND_LIST",
    SEARCH_DETAIL: "SEARCH_DETAIL",
    CONTACT_LIST: "CONTACT_LIST",
    CONTACT_DETAIL: "CONTACT_DETAIL",
    DASHBOARD: "DASHBOARD",
    ALERT_MSG: "ALERT_MSG"
};

const MenuAction = {
    MINI_SIDENAV: "MINI_SIDENAV",
    TRANSPARENT_NAVBAR: "TRANSPARENT_NAVBAR",
    FIXED_NAVBAR: "FIXED_NAVBAR",
    LAYOUT: "LAYOUT",
};

export { ActionTypes, MenuAction };